### ISSUE TITLE
Region Mismatch

### ISSUE THREAD

**Issue by crazix** [dekiller82/Spotify-Playlist-Downloader-GUI#5]
Hi there,

I am new to GitHub. I am in love with your project Spotify Playlist Downloader.
I am facing a weird issue. As I am from India, recently I am not able to download as I am getting region mismatch error. I tried using VPN too still fails to work.

**Comment by ghost** [comment]
1. Open "downloader.js" file in text editor (like Notepad).
2. Search the line nº 83, wich determines the Spotify country. By default, is set to "DE" (Germany).
3. Change it to India "IN" and re-run the program
