### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [dekiller82/Spotify-Playlist-Downloader-GUI#7]
.

**Comment by ghost** [comment]
Not. All of us have the same problem. @dekiller82  is working on it.

Please be patient.

**Comment by morganjacklee** [comment]
Will do. Thanks!

**Comment by crazix** [comment]
Today I noticed, I am able to download mp3s directly from spotify through IDM was super excited till it failed to play. Error: Windows Media Player encountered a problem while playing the file. :(

Hope @dekiller82 is able to fix the problem :)

**Comment by nestoroa** [comment]
I really wish i could solve it by myself, i love this program.
