### ISSUE TITLE
Doesn't enter capcha

### ISSUE THREAD

**Issue by FractumSeraph** [dekiller82/Spotify-Playlist-Downloader-GUI#8]
I realize this is pretty old, but is there any chance someone knows how to make this thing log in? It's trying to log in without doing the capcha.

Also, for some reason nodejs installs to Program Files (x86) even if you use the 64-bit version, which will cause this to crash do to line 291.

**Comment by ghost** [comment]
It doesn't work. Spotify blocked it, plus there's the login issue.
